baseURL = "https://feresignum.com/"
languageCode = "en-us"
title = "Feresignum"
theme = "coder"
pagination.pagerSize = 5
pygmentsStyle = "friendly"
pygmentsCodefences = true
assetDir = "assets"

[permalinks]
  posts = "/:slug"

[params]
  description = "Of random bits and bytes"
  featured_image = "/images/flair.png"
  author = "Sidney Just"