baseURL = "https://feresignum.com/"
languageCode = "en-us"
title = "feresignum"
theme = "coder"
paginate = 5
pygmentsStyle = "friendly"
pygmentsCodefences = true

[permalinks]
  posts = "/:slug"

[params]
  description = "Of random bits and bytes"
  featured_image = "/images/flair.png"